#DELETE http://{{ip}}:{{port}}/api/v1/books/1
#Accept: application/json
#
####

GET http://{{ip}}:{{port}}/api/v1/books/
Accept: application/json

###
POST http://{{ip}}:{{port}}/api/v1/books/
Content-Type: application/json

{
  "books": [
    {
      "name": "KVM 虚拟机高级管理",
      "author": ["胡金庸","聂安泰"],
      "publisher": ["中国教育出版社","清华大学出版社"]
    }
  ]
}

###


GET http://{{ip}}:{{port}}/api/v1/admin/
Accept: application/json

###


