DELETE http://{{url}}/authors/
Content-Type: application/json

{
  "author_ids": [
    1,
    3
  ]
}

###

GET http://{{url}}/authors/{{$randomInt}}
Accept: application/json

###


GET http://{{url}}/authors/
Accept: application/json

###
