DELETE http://{{url}}/books/
Content-Type: application/json

{
  "book_ids": [1,3]
}

###
POST http://{{url}}/books/
Content-Type: application/json

{
  "books": [
    {
      "name": "C# 程序设计{{$randomInt}}",
      "authors": [
        {
          "name": "曾宪权"
        },
        {
          "name": "曹玉松"
        },
        {
          "name": "鄢靖丰"
        }
      ],
      "isbn": "978730257{{$randomInt}}",
      "publication_date": "2021-02-15"
    }
  ]
}

###

###
GET http://{{url}}/books
Accept: application/json

###




