POST http://{{url}}/books/add
Content-Type: application/json

{
  "books": [
    {
      "name": "F# 程序设计与应用开发",
      "authors": [
        {
          "name": "曾宪权"
        },
        {
          "name": "曹玉松"
        },
        {
          "name": "鄢靖丰"
        }
      ],
      "isbn": "9787302571832",
      "publication_date": "2021-02-15"
    }
  ]
}

###

###
GET http://{{url}}/books
Accept: application/json

###




