POST http://{{url}}/authors/
Content-Type: application/json

{
  "authors": [
    {
      "name": "NIEANTAIsd11"
    },
    {
      "name": "HUJINYONsdd23G1"
    }
  ]
}

###
GET http://{{url}}/authors/
Accept: application/json

####

DELETE http://{{url}}/authors/
Content-Type: application/json

{
  "authors_id": [
    11,
    10
  ]
}

###

PUT http://{{url}}/authors/9
Accept: application/json
Content-Type: application/json

{
  "name": "NIsdssdassdadaassEANTAI1",
  "phone": "saassss",
  "addr": "test"
}

###