"""empty message

Revision ID: d3aa03b78d77
Revises: 
Create Date: 2023-08-10 16:48:31.189226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3aa03b78d77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_authors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('addr', sa.String(length=80), nullable=True),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('db_books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('data_publish', sa.DateTime(), nullable=True),
    sa.Column('count_page', sa.String(length=10), nullable=True),
    sa.Column('version', sa.String(length=10), nullable=True),
    sa.Column('recomLevel', sa.String(length=10), nullable=True),
    sa.Column('url', sa.String(length=50), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('book_m2m_author',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['db_authors.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['db_books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_m2m_author')
    op.drop_table('db_books')
    op.drop_table('db_authors')
    # ### end Alembic commands ###
